version: '3'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: SQLSERVER
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Teste@123
    ports:
      - "1433:1433"
    volumes:
      - .\Database:/var/opt/mssql/data
    networks:
      - proxy

  api:
    build:
      context: .
      dockerfile: Api/Dockerfile
    container_name: api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6000:80"
      - "6001:443"
    depends_on:
      - sqlserver
    networks:
      - proxy

  client:
    build:
      context: .
      dockerfile: Client/Dockerfile
    container_name: client
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7000:80"
      - "7001:443"
    depends_on:
      - sqlserver
      - api
    networks:
      - proxy

networks:
  patterns-network:
    driver: 'proxy'
